In [2]:
#THIS IS A NOTEBOOK FOR CREATING A TABLE THAT HAS INFORMATION ABOUT THE ACCIDENT AND ADDITIONALY WHAT WAS THE CLOSEST TRAFFIC FEATURE AND HOW FAR AWAY WAS IT
#To run this you will need ipython-sql package

import sqlite3
%load_ext sql

In [3]:
#connect to a database
%sql sqlite:///./database.db

In [32]:
%%sql

ALTER TABLE liiklusonnetus ADD COLUMN closest_feature TEXT;
ALTER TABLE liiklusonnetus ADD COLUMN distance REAL;

 * sqlite:///./database.db
Done.
Done.

[]

In [15]:
%%sql

ALTER TABLE seadmed
ADD COLUMN coordinates TEXT;
UPDATE seadmed
SET coordinates = Lat || ',' || Lon;

 * sqlite:///./database.db
Done.
118 rows affected.

[]

In [31]:
%%sql

SELECT * FROM seadmed LIMIT 5;

 * sqlite:///./database.db
Done.

[('LOO 1_13236 VBV', '0cfcf', 1, 13.2, 'Harjumaa', 24.96457, 59.44959, '59.44959,24.96457'),
 ('PRÜGILA RIST 1_17794 VBV', '25785', 1, 17.79, 'Harjumaa', 25.0444336, 59.45134, '59.45134,25.0444336'),
 ('KODASOO 1_32100 VBV', '077a6', 1, 32.1, 'Harjumaa', 25.29038, 59.44065, '59.44065,25.29038'),
 ('VIITNA 1_73241 VBV', '67241', 1, 73.2, 'Lääne-Virumaa', 26.00836, 59.46308, '59.46308,26.00836'),
 ('SÄMI 1_109455 VBV', '387ad', 1, 109.4, 'Lääne-Virumaa', 26.58264, 59.37418, '59.37418,26.58264')]

In [33]:
%%sql

ALTER TABLE liiklusonnetus
ADD COLUMN coordinates TEXT;
UPDATE liiklusonnetus
SET coordinates = Latitude || ',' || Longitude;

 * sqlite:///./database.db
Done.
8045 rows affected.

[]

In [15]:
%%sql

SELECT * FROM liiklusonnetus LIMIT 5;

 * sqlite:///./database.db
Done.

[(2000140000057, '2014-10-24 08:45:00', 'JAH', 'Kokkupõrge jalakäijaga', 6588678.0, 542647.0, 24, 10, 2014, 8, 45, 24.751478719314402, 59.43379595290958, 'KODASOO 1_32100 VBV', 0.0002315099069037317, '59.4337959529096,24.7514787193144'),
 (2000140000067, '2014-10-24 13:45:00', 'JAH', 'Kokkupõrge ees liikuva sõidukiga', 6589522.0, 541467.0, 24, 10, 2014, 13, 45, 24.730849754494095, 59.44148846858757, 'KODASOO 1_32100 VBV', 0.0002315099069037317, '59.4414884685876,24.7308497544941'),
 (2000140000235, '2014-11-17 17:32:00', 'EI', 'Kokkupõrge vastutuleva sõidukiga', 6569324.0, 516628.0, 17, 11, 2014, 17, 32, 24.29152856115738, 59.26188409298865, 'KODASOO 1_32100 VBV', 0.0002315099069037317, '59.2618840929887,24.2915285611574'),
 (2000150000442, '2015-04-28 07:55:00', 'JAH', 'Kokkupõrge sõidukiga küljelt', 6586430.0, 541953.0, 28, 4, 2015, 7, 55, 24.738814527574075, 59.413687705501715, 'KODASOO 1_32100 VBV', 0.0002315099069037317, '59.4136877055017,24.7388145275741'),
 (2210140001932, '2014-10-24 14:00:00', 'EI', 'Kokkupõrge vastutuleva sõidukiga', 6575538.0, 529034.0, 24, 10, 2014, 14, 0, 24.509856888443853, 59.31699930958726, 'KODASOO 1_32100 VBV', 0.0002315099069037317, '59.3169993095873,24.5098568884439')]

In [13]:
%%sql

SELECT Juhtumi_nr, Name, SQRT (POW(Longitude - Lon, 2) + POW(Latitude - Lat, 2)) * 111.3 AS Kaugus FROM liiklusonnetus, seadmed LIMIT 150;

 * sqlite:///./database.db
Done.

[(2000140000057, 'LOO 1_13236 VBV', 23.78211610300087),
 (2000140000057, 'PRÜGILA RIST 1_17794 VBV', 32.664294666707356),
 (2000140000057, 'KODASOO 1_32100 VBV', 59.984563554650975),
 (2000140000057, 'VIITNA 1_73241 VBV', 139.92885073371903),
 (2000140000057, 'SÄMI 1_109455 VBV', 203.91623183217095),
 (2000140000057, 'VARJA 1_146054 VBV', 266.63759037899337),
 (2000140000057, 'KUKRUSE 1_158295 VBV', 287.5134495588543),
 (2000140000057, 'KONJU 1_176970 VBV', 320.00216003463254),
 (2000140000057, 'SINIMÄE 1_194738 VBV', 354.77667321622147),
 (2000140000057, 'PEETRI 2_7050 VBV', 9.716237049366647),
 (2000140000057, 'PATIKA 2_17200 VBV', 23.73667448219274),
 (2000140000057, 'ARUVALLA 2_25900 VBV', 35.593594018168424),
 (2000140000057, 'KUIVAJÕE 2_34849', 45.75409141980083),
 (2000140000057, 'KOSE-RISTI 2_44300 VBV', 60.92344970639192),
 (2000140000057, 'USSISOO 2_69483 VBV', 94.40057956046273),
 (2000140000057, 'PIKAKÜLA 2_82335 VBV', 108.52208601371805),
 (2000140000057, 'MÄEKÜLA 2_92719', 120.02343344572444),
 (2000140000057, 'PIKKNURME 2_144492 VBV', 191.46449331811846),
 (2000140000057, 'KÄREVERE 2_164771 VBV', 216.85532580724043),
 (2000140000057, 'KANDIKÜLA 2_181691 VBV', 243.6025300265486),
 (2000140000057, 'ÜLENURME 2_191800 VBV', 252.52097745486338),
 (2000140000057, 'TATRA 2_196968 VBV', 251.92843749076755),
 (2000140000057, 'HEIMTALI 2_238202 VBV', 285.3085114826214),
 (2000140000057, 'TOOTSI 2_260436 VBV', 316.38084665986946),
 (2000140000057, 'MÄETAGUSE 3_21720 VBV', 289.98253452323877),
 (2000140000057, 'TAMMISPÄÄ 3_62173 VBV', 258.22836465939986),
 (2000140000057, 'PATASTE 3_109883 VBV', 243.55802621036253),
 (2000140000057, 'KÕRVEKÜLA 3_124984 VBV', 252.32502876737345),
 (2000140000057, 'KÜLITSE 3_142480 VBV', 243.36053702748615),
 (2000140000057, 'TÕRAVERE 3_154111 VBV', 232.48810635191515),
 (2000140000057, 'PUKA 3_185450 VBV', 222.30545172921714),
 (2000140000057, 'PAJU 3_213030 VBV', 234.1380098866604),
 (2000140000057, 'LAAGRI 4_12947 VBV', 16.346712832997703),
 (2000140000057, 'PEOLEO 4_15639 VBV', 19.982343080780552),
 (2000140000057, 'KANAMA 4_21160 VBV', 27.754819447158212),
 (2000140000057, 'VAIMÕISA 4_57401 VBV', 59.07665864858658),
 (2000140000057, 'ARE 4_107900 VBV', 101.0577764105797),
 (2000140000057, 'PÄRNU 4_123000 VBV', 116.13595880631738),
 (2000140000057, 'REIU 4_140354 VBV', 126.8849380475325),
 (2000140000057, 'VÕISTE 4_151965 VBV', 136.86970623235757),
 (2000140000057, 'IKLA 4_189000 VBV', 174.6474432716096),
 (2000140000057, 'TORI 5_22928 VBV', 102.83565259449519),
 (2000140000057, 'REOPALU 5_85515 VBV', 103.94383565261091),
 (2000140000057, 'MÄO 2 5_96549 VBV', 112.67924808167561),
 (2000140000057, 'MÄO 1 5_94349 VBV', 110.85432679708748),
 (2000140000057, 'KADRINA 5_155812 VBV', 149.7770988078185),
 (2000140000057, 'HELME 6_34735 VBV', 197.16771883090522),
 (2000140000057, 'MÕISAKÜLA 6 _77717 VBV', 156.4797997395958),
 (2000140000057, 'RISTIKÜLA 6_107568 VBV', 139.05614291089856),
 (2000140000057, 'MURATI 7_182380 VBV', 329.3243472586459),
 (2000140000057, 'HÜÜRU 8_17080 VBV', 27.32295221161184),
 (2000140000057, 'KLOOGARANNA 8_39400 VBV', 61.138800519502745),
 (2000140000057, 'HARUTEE 9_1200 VBV', 37.16857820614902),
 (2000140000057, 'RISTI 9_38225', 88.23403512785188),
 (2000140000057, 'HERJAVA 9_64734 VBV', 132.93947230388528),
 (2000140000057, 'ROHUKÜLA 9_78989 VBV', 155.72083370218488),
 (2000140000057, 'KOLUVERE 10_5700 VBV', 91.92852543322084),
 (2000140000057, 'LIHULA 10_37238 VBV', 122.51891140957585),
 (2000140000057, 'VALUSTE 10_46600 VBV', 137.13161187142853),
 (2000140000057, 'KUIVASTU 10_70004 VBV', 181.61527493167208),
 (2000140000057, 'VALJALA 10_118459 VBV', 247.63302556726907),
 (2000140000057, 'KARLA1_11_7878 VBV VDA', 19.182153255179344),
 (2000140000057, 'KARLA2_11_9120 VBV VDA', 18.46838427482934),
 (2000140000057, 'VAELA 11_15733 VBV VDA', 12.512083951209005),
 (2000140000057, 'JUULIKU 11_25574 VBV', 17.132452104128554),
 (2000140000057, 'JÄGALA 13_2245', 51.67395398913406),
 (2000140000057, 'JÄNEDA 13_42278 VBV', 104.13394121038313),
 (2000140000057, 'KANGRU 15_4617 VBV', 8.489394064340297),
 (2000140000057, 'LOKUTI 15_13400 VBV', 16.706400473071373),
 (2000140000057, 'URGE 15_23400 VBV', 26.279316434288415),
 (2000140000057, 'KOHILA 15_34693 VBV', 36.6439761337489),
 (2000140000057, 'KEHTNA 15_59718 VBV', 59.3414255513156),
 (2000140000057, 'MAERU 17_10554 VBV', 54.57386417012519),
 (2000140000057, 'ESSU 20_3876 VBV', 182.17147392594174),
 (2000140000057, 'KARKUSE 21_5921 VBV', 183.33994211813064),
 (2000140000057, 'ASSAMALLA 22_14416 VBV', 169.85887792873575),
 (2000140000057, 'HALJALA 23_7803 VBV', 170.44016751842565),
 (2000140000057, 'RAUKLA 26_6000 VBV', 113.15253619245132),
 (2000140000057, 'KUUSIKU 28_5041 VBV', 51.65551651338648),
 (2000140000057, 'LAIKÜLA 31_28388 VBV', 120.47720410434282),
 (2000140000057, 'LAIUSE 36_14218 VBV', 211.93075434416835),
 (2000140000057, 'KAAVERE 37_13777 VBV', 176.0357092758314),
 (2000140000057, 'MARAMAA 39_3379 VBV', 241.74470895840633),
 (2000140000057, 'LÄHTE 39_9832 VBV', 239.20401137488054),
 (2000140000057, 'KASSINURME 39_37615 VBV', 206.1000096229193),
 (2000140000057, 'TÄHTVERE 40_4214 VBV', 244.22431895235098),
 (2000140000057, 'VANA-KASTRE 45_12240 VBV', 268.8383597473923),
 (2000140000057, 'TATRA 46_794 VBV', 251.21937500878775),
 (2000140000057, 'SÜRGAVERE 49_33509 VBV', 139.99407713284535),
 (2000140000057, 'LOODI 49_60583', 159.44216087098616),
 (2000140000057, 'VIIRATSI 52_765 VBV', 154.54958405901752),
 (2000140000057, 'PAIKUSE 59_2372 VBV', 119.48281085286011),
 (2000140000057, 'AUDRU 60_13100 VBV', 123.25866175005669),
 (2000140000057, 'VASTSE-KUUSTE 61_18159 VBV', 275.8212684775636),
 (2000140000057, 'JOOSU 64_11400 VBV', 304.9966702538086),
 (2000140000057, 'VARSTU 67_33864 VBV', 290.4376063741313),
 (2000140000057, 'LINNAMÄE 69_15300 VBV', 278.50982984866323),
 (2000140000057, 'PARILA 78_4627 VBV', 288.16616666232574),
 (2000140000057, 'PARTSI 80_19602 VBV', 220.61433888757483),
 (2000140000057, 'KOLGAKÜLA 85_8260 VBV', 106.0156474956334),
 (2000140000057, 'TÕRVAJÕE 91_9075 VBV', 374.66844269333484),
 (2000140000057, 'KAIMI 92_17000 VBV', 218.53371721074345),
 (2000140000057, 'TEEMEISTRI 92_69800 VBV', 154.86850474866483),
 (2000140000057, 'KANAKÜLA 92_101944 VBV', 141.4988260845441),
 (2000140000057, 'JÄRVE 93_9202 VBV', 286.0992514233783),
 (2000140000057, 'RANDVERE 11250_621 VBV', 11.51556585270137),
 (2000140000057, 'ROHUNEEME 11251_953 VBV', 11.559412164222033),
 (2000140000057, 'KAKUMÄE 11390_3700 VBV', 18.494009093692373),
 (2000140000057, 'JUULIKU 11420_3350 VBV', 17.701973416427624),
 (2000140000057, 'AHTME 3_3747 VBV', 295.5782410756072),
 (2000140000057, 'JÄMEJALA 50_944 VBV', 148.49464411718327),
 (2000140000057, 'KUPU 1_45065 VBV', 85.22006887645057),
 (2000140000057, 'KURNA 11_12687 VBV', 15.286315257988997),
 (2000140000057, 'MÄRJA 92_697 VBV VDA', 237.5519624518383),
 (2000140000057, 'OLGINA 1_206400 VBV', 373.0163303164844),
 (2000140000057, 'PAPPSAARE1 60_4940 VBV', 120.51885714914515),
 (2000140000057, 'PAPPSAARE2 60_4940 VBV', 120.54012802703363),
 (2000140000057, 'TAMMEMÄE 11_23189 VBV', 14.986905555109072),
 (2000140000067, 'LOO 1_13236 VBV', 26.028686621401118),
 (2000140000067, 'PRÜGILA RIST 1_17794 VBV', 34.91910116084929),
 (2000140000067, 'KODASOO 1_32100 VBV', 62.27578624698569),
 (2000140000067, 'VIITNA 1_73241 VBV', 142.20719689883526),
 (2000140000067, 'SÄMI 1_109455 VBV', 206.24035786550837),
 (2000140000067, 'VARJA 1_146054 VBV', 268.94111995210204),
 (2000140000067, 'KUKRUSE 1_158295 VBV', 289.8229395239918),
 (2000140000067, 'KONJU 1_176970 VBV', 322.3109511550443),
 (2000140000067, 'SINIMÄE 1_194738 VBV', 357.08897295864375),
 (2000140000067, 'PEETRI 2_7050 VBV', 12.142018626014984),
 (2000140000067, 'PATIKA 2_17200 VBV', 26.132272350967337),
 (2000140000067, 'ARUVALLA 2_25900 VBV', 37.97384001454544),
 (2000140000067, 'KUIVAJÕE 2_34849', 48.102434438985945),
 (2000140000067, 'KOSE-RISTI 2_44300 VBV', 63.33344135467064),
 (2000140000067, 'USSISOO 2_69483 VBV', 96.82839891842727),
 (2000140000067, 'PIKAKÜLA 2_82335 VBV', 110.94694559363093),
 (2000140000067, 'MÄEKÜLA 2_92719', 122.4371717613762),
 (2000140000067, 'PIKKNURME 2_144492 VBV', 193.8862553744928),
 (2000140000067, 'KÄREVERE 2_164771 VBV', 219.26928206266248),
 (2000140000067, 'KANDIKÜLA 2_181691 VBV', 246.02802059614802),
 (2000140000067, 'ÜLENURME 2_191800 VBV', 254.9386095175772),
 (2000140000067, 'TATRA 2_196968 VBV', 254.33629342106667),
 (2000140000067, 'HEIMTALI 2_238202 VBV', 287.6662352715802),
 (2000140000067, 'TOOTSI 2_260436 VBV', 318.75359372558023),
 (2000140000067, 'MÄETAGUSE 3_21720 VBV', 292.34766548500625),
 (2000140000067, 'TAMMISPÄÄ 3_62173 VBV', 260.6565148545269),
 (2000140000067, 'PATASTE 3_109883 VBV', 246.0043350561006),
 (2000140000067, 'KÕRVEKÜLA 3_124984 VBV', 254.7624938146659),
 (2000140000067, 'KÜLITSE 3_142480 VBV', 245.77371813851593),
 (2000140000067, 'TÕRAVERE 3_154111 VBV', 234.86986539969288),
 (2000140000067, 'PUKA 3_185450 VBV', 224.5574390659428),
 (2000140000067, 'PAJU 3_213030 VBV', 236.27602004790856)]

In [14]:
%%sql

SELECT Juhtumi_nr, Name, MIN(SQRT(POW(Longitude - Lon, 2) + POW(Latitude - Lat, 2)) * 111.3) AS Kaugus
FROM liiklusonnetus, seadmed
GROUP BY Juhtumi_nr LIMIT 10;

 * sqlite:///./database.db
Done.

[(2000140000057, 'KANGRU 15_4617 VBV', 8.489394064340297),
 (2000140000067, 'KANGRU 15_4617 VBV', 10.04150858395428),
 (2000140000235, 'MAERU 17_10554 VBV', 0.1984170354295271),
 (2000150000442, 'KANGRU 15_4617 VBV', 6.874770151903621),
 (2210140001932, 'KANAMA 4_21160 VBV', 4.824827640215788),
 (2230130056988, 'PEETRI 2_7050 VBV', 5.215681916855247),
 (2230140051396, 'LAAGRI 4_12947 VBV', 7.210237727250402),
 (2300140000454, 'KANGRU 15_4617 VBV', 7.9360704921118055),
 (2300140000817, 'KANGRU 15_4617 VBV', 8.765908911686635),
 (2300140001423, 'KARLA1_11_7878 VBV VDA', 0.79714639055749)]

In [16]:
%%sql


Create VIEW v_koord_kaugused AS SELECT Juhtumi_nr, Name, MIN(SQRT(POW(Longitude - Lon, 2) + POW(Latitude - Lat, 2)) * 111.3) AS Kaugus
FROM liiklusonnetus, seadmed
GROUP BY Juhtumi_nr LIMIT 10;

 * sqlite:///./database.db
Done.

[]

In [17]:
%%sql
SELECT* FROM v_koord_kaugused Limit 5;

 * sqlite:///./database.db
Done.

[(2000140000057, 'KANGRU 15_4617 VBV', 8.489394064340297),
 (2000140000067, 'KANGRU 15_4617 VBV', 10.04150858395428),
 (2000140000235, 'MAERU 17_10554 VBV', 0.1984170354295271),
 (2000150000442, 'KANGRU 15_4617 VBV', 6.874770151903621),
 (2210140001932, 'KANAMA 4_21160 VBV', 4.824827640215788)]

In [21]:
%%sql

UPDATE liiklusonnetus 
   SET closest_feature=(SELECT Name FROM v_koord_kaugused WHERE liiklusonnetus.Juhtumi_nr=v_koord_kaugused.Juhtumi_nr);

 * sqlite:///./database.db
8045 rows affected.

[]

In [24]:
%%sql
SELECT * FROM liiklusonnetus LIMIT 10;

 * sqlite:///./database.db
Done.

[(2000140000057, '2014-10-24 08:45:00', 'JAH', 'Kokkupõrge jalakäijaga', 6588678.0, 542647.0, 24, 10, 2014, 8, 45, 24.751478719314402, 59.43379595290958, 'KANGRU 15_4617 VBV', 8.489394064340297, '59.4337959529096,24.7514787193144'),
 (2000140000067, '2014-10-24 13:45:00', 'JAH', 'Kokkupõrge ees liikuva sõidukiga', 6589522.0, 541467.0, 24, 10, 2014, 13, 45, 24.730849754494095, 59.44148846858757, 'KANGRU 15_4617 VBV', 10.04150858395428, '59.4414884685876,24.7308497544941'),
 (2000140000235, '2014-11-17 17:32:00', 'EI', 'Kokkupõrge vastutuleva sõidukiga', 6569324.0, 516628.0, 17, 11, 2014, 17, 32, 24.29152856115738, 59.26188409298865, 'MAERU 17_10554 VBV', 0.1984170354295271, '59.2618840929887,24.2915285611574'),
 (2000150000442, '2015-04-28 07:55:00', 'JAH', 'Kokkupõrge sõidukiga küljelt', 6586430.0, 541953.0, 28, 4, 2015, 7, 55, 24.738814527574075, 59.413687705501715, 'KANGRU 15_4617 VBV', 6.874770151903621, '59.4136877055017,24.7388145275741'),
 (2210140001932, '2014-10-24 14:00:00', 'EI', 'Kokkupõrge vastutuleva sõidukiga', 6575538.0, 529034.0, 24, 10, 2014, 14, 0, 24.509856888443853, 59.31699930958726, 'KANAMA 4_21160 VBV', 4.824827640215788, '59.3169993095873,24.5098568884439'),
 (2230130056988, '2013-11-18 08:50:00', 'JAH', 'Kokkupõrge jalakäijaga', 6589152.0, 546923.0, 18, 11, 2013, 8, 50, 24.82692138353671, 59.437598819978064, 'PEETRI 2_7050 VBV', 5.215681916855247, '59.4375988199781,24.8269213835367'),
 (2230140051396, '2014-07-14 19:53:00', 'JAH', 'Kokkupõrge jalakäijaga', 6583421.0, 538871.0, 14, 7, 2014, 19, 53, 24.684002458093488, 59.38697273814245, 'LAAGRI 4_12947 VBV', 7.210237727250402, '59.3869727381424,24.6840024580935'),
 (2300140000454, '2014-08-15 10:25:00', 'JAH', 'Kokkupõrge ees liikuva sõidukiga', 6588058.0, 542554.0, 15, 8, 2014, 10, 25, 24.749718009373705, 59.428240360130765, 'KANGRU 15_4617 VBV', 7.9360704921118055, '59.4282403601308,24.7497180093737'),
 (2300140000817, '2014-10-20 01:54:00', 'JAH', 'Kokkupõrge sõidukiga küljelt', 6588441.0, 541837.0, 20, 10, 2014, 1, 54, 24.7371610539775, 59.431749389336545, 'KANGRU 15_4617 VBV', 8.765908911686635, '59.4317493893365,24.7371610539775'),
 (2300140001423, '2014-11-21 10:04:00', 'EI', 'Kokkupõrge vastutuleva sõidukiga', 6581844.0, 551674.0, 21, 11, 2014, 10, 4, 24.90889322342989, 59.371453325790505, 'KARLA1_11_7878 VBV VDA', 0.79714639055749, '59.3714533257905,24.9088932234299')]

In [23]:
%%sql

UPDATE liiklusonnetus 
   SET distance=(SELECT Kaugus FROM v_koord_kaugused WHERE liiklusonnetus.Juhtumi_nr=v_koord_kaugused.Juhtumi_nr);

 * sqlite:///./database.db
8045 rows affected.

[]

In [25]:
%%sql
SELECT * FROM liiklusonnetus LIMIT 10;

 * sqlite:///./database.db
Done.

[(2000140000057, '2014-10-24 08:45:00', 'JAH', 'Kokkupõrge jalakäijaga', 6588678.0, 542647.0, 24, 10, 2014, 8, 45, 24.751478719314402, 59.43379595290958, 'KANGRU 15_4617 VBV', 8.489394064340297, '59.4337959529096,24.7514787193144'),
 (2000140000067, '2014-10-24 13:45:00', 'JAH', 'Kokkupõrge ees liikuva sõidukiga', 6589522.0, 541467.0, 24, 10, 2014, 13, 45, 24.730849754494095, 59.44148846858757, 'KANGRU 15_4617 VBV', 10.04150858395428, '59.4414884685876,24.7308497544941'),
 (2000140000235, '2014-11-17 17:32:00', 'EI', 'Kokkupõrge vastutuleva sõidukiga', 6569324.0, 516628.0, 17, 11, 2014, 17, 32, 24.29152856115738, 59.26188409298865, 'MAERU 17_10554 VBV', 0.1984170354295271, '59.2618840929887,24.2915285611574'),
 (2000150000442, '2015-04-28 07:55:00', 'JAH', 'Kokkupõrge sõidukiga küljelt', 6586430.0, 541953.0, 28, 4, 2015, 7, 55, 24.738814527574075, 59.413687705501715, 'KANGRU 15_4617 VBV', 6.874770151903621, '59.4136877055017,24.7388145275741'),
 (2210140001932, '2014-10-24 14:00:00', 'EI', 'Kokkupõrge vastutuleva sõidukiga', 6575538.0, 529034.0, 24, 10, 2014, 14, 0, 24.509856888443853, 59.31699930958726, 'KANAMA 4_21160 VBV', 4.824827640215788, '59.3169993095873,24.5098568884439'),
 (2230130056988, '2013-11-18 08:50:00', 'JAH', 'Kokkupõrge jalakäijaga', 6589152.0, 546923.0, 18, 11, 2013, 8, 50, 24.82692138353671, 59.437598819978064, 'PEETRI 2_7050 VBV', 5.215681916855247, '59.4375988199781,24.8269213835367'),
 (2230140051396, '2014-07-14 19:53:00', 'JAH', 'Kokkupõrge jalakäijaga', 6583421.0, 538871.0, 14, 7, 2014, 19, 53, 24.684002458093488, 59.38697273814245, 'LAAGRI 4_12947 VBV', 7.210237727250402, '59.3869727381424,24.6840024580935'),
 (2300140000454, '2014-08-15 10:25:00', 'JAH', 'Kokkupõrge ees liikuva sõidukiga', 6588058.0, 542554.0, 15, 8, 2014, 10, 25, 24.749718009373705, 59.428240360130765, 'KANGRU 15_4617 VBV', 7.9360704921118055, '59.4282403601308,24.7497180093737'),
 (2300140000817, '2014-10-20 01:54:00', 'JAH', 'Kokkupõrge sõidukiga küljelt', 6588441.0, 541837.0, 20, 10, 2014, 1, 54, 24.7371610539775, 59.431749389336545, 'KANGRU 15_4617 VBV', 8.765908911686635, '59.4317493893365,24.7371610539775'),
 (2300140001423, '2014-11-21 10:04:00', 'EI', 'Kokkupõrge vastutuleva sõidukiga', 6581844.0, 551674.0, 21, 11, 2014, 10, 4, 24.90889322342989, 59.371453325790505, 'KARLA1_11_7878 VBV VDA', 0.79714639055749, '59.3714533257905,24.9088932234299')]